# Maximum width of the sprite sheet
max_width : 512

# Horizontal gap between sprites
x_gap : 3

# Vertical gap between sprites
y_gap : 3

# Common badge size
common_badge_size : 19

# root layer name to use as sprite area
root_layer_prefix : %

# skip layer groups that haven't been upgraded
skip_layer_prefix : ~

# layer name of layout area
area_layer_prefix : badge

# layer name of hit area
hit_layer_prefix : hitarea

# layer name of filter area
# Implied that "filter: " on interpretation in the JSX
filter_layer_prefix : filter

# layer name of zoom filter
# Implied that "zoom: " on interpretation in the JSX
zoom_filter_layer_prefix : zoom

# export area (badge) layer
export_area_layer : true

# export as black and white mask (accepts "true" or "false")
export_as_black_and_white_mask : false

# export as grey mask (accepts "true" or "false")
export_as_grey_mask : false

# export filetype (accepts "png24", "png8", or "jpg" or "svg")
export_format : png24

# export resolution (1, 2, 3)
export_resolution : 2

# quality of jpg export (accepts 0-100)
jpg_quality : 30

# output file name
output_filename : poi_icons_18 # this is not used anymore, taken from AI file name at runtime

# whether to generate HTML (accepts "true" or "false")
generate_html : false

# whether to generate CSS (accepts "true" or "false")
generate_css : true

# should we assume the sprite name is the filter name? If so, don't export filters except when custom
generate_css_using_filter_auto_lookup : true

# whether to generate parameters (accepts "true" or "false")
generate_param : false

# output format. This is a single entry in the output file script. Script will search for prefixes (from above) and inject full layer name and associated value
# prefixes here MUST match above sprite and hit area layer prefixes!
param_format : "sprite_":{"sprite_x":"sprite_x_value","sprite_y":"sprite_y_value","sprite_width":"sprite_width_value","sprite_height":"sprite_height_value","sprite_hit_x":"sprite_hit_x_value","sprite_hit_y":"sprite_hit_y_value","sprite_hit_width":"sprite_hit_width_value","sprite_hit_height":"sprite_hit_height_value","sprite_filter":"sprite_filter_value"}

# type of parameter data (accepts "json") # TODO add "xml", "array"
param_type : json

# move sprites into compact sprite sheet grid before export
move_sprites_to_new_grid : true

# preserve new grid layout after export
preserve_grid : false
